#ifndef RMI_VERSION_H
#define RMI_VERSION_H

#define RMI_VERSION_MAJOR "1"
#define RMI_VERSION_MINOR "8"
#define RMI_VERSION_SUBMINOR "7"

#define RMI_VERSION_BRANCH "mako"
#define RMI_EXTRA_NUMBER "1"
#define RMI_EXTRA_STRING "mako.0"

#define RMI_DRIVER_VERSION RMI_VERSION_MAJOR "." \
	RMI_VERSION_MINOR "." RMI_VERSION_SUBMINOR "-" \
	RMI_EXTRA_STRING

#endif
